name=MyGpio
version=1.0.0
author=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
maintainer=Eric VINSONNAUD <eric.vinsonnaud@gmail.com>
sentence=A simple library for managing GPIOs.
paragraph=This library allows you to easily manage GPIOs and extend them with classes like Led, Button, etc.
category=Other
url=https://github.com/ricodev38/MyGpioLib
architectures=*
includes=Gpio.h
